IF
	Global("OH_Active","LOCALS",0)
	OR(3)
		See(NearestEnemyOf(Myself))
		AttackedBy([ANYONE],DEFAULT)
		TookDamage()
THEN
	RESPONSE #100
		SetGlobal("OH_Active","LOCALS",1)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		Enemy()
		Shout(ASSIST)
		Continue()
END

IF
	Global("OH_Active","LOCALS",0)
	Heard([EVILCUTOFF],ASSIST)
	Range(LastHeardBy(Myself),25)
THEN
	RESPONSE #100
		SetGlobal("OH_Active","LOCALS",1)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		Enemy()
		Shout(ASSIST)
		MoveToObject(LastHeardBy(Myself))
END

IF
	OR(4)
		Global("OH_Active","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!GlobalTimerNotExpired("OH_Rest","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		ApplySpell(Myself,RESTORE_FULL_HEALTH) // SPIN746.SPL (No such index)
		SetGlobal("OH_Dfear","LOCALS",0)
		Rest()
END

IF
	Global("OH_Active","LOCALS",1)
	!InActiveArea(Myself)
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		NoAction()
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	Global("OH_Dfear","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("OH_Dfear","LOCALS",1)
		ReallyForceSpellRES("OHBDRAG2",LastSeenBy(Myself)) // Dragon Fear
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast([GOODCUTOFF.0.0.LONG_BOW],WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast([GOODCUTOFF.0.0.LONG_BOW],WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast([GOODCUTOFF.0.0.LONG_BOW],WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast([GOODCUTOFF.0.0.LONG_BOW],WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	!GlobalTimerNotExpired("OH_WingB","LOCALS")
	Global("OH_Cloud","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_WingB","LOCALS",THREE_ROUNDS)
		SetGlobal("OH_Cloud","LOCALS",0)
		ForceSpell(Myself,DRAGON_WING_BUFFET) // SPIN695.SPL (Wing Buffet)
END

IF
	!GlobalTimerNotExpired("OH_WingB","LOCALS")
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
	OR(3)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),3,NUMBEROFATTACKS)
		RandomNum(5,1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_WingB","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET) // SPIN695.SPL (Wing Buffet)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_WingB","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
	OR(3)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),3,NUMBEROFATTACKS)
		RandomNum(5,1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_WingB","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET) // SPIN695.SPL (Wing Buffet)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_WingB","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
	OR(3)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),3,NUMBEROFATTACKS)
		RandomNum(5,1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_WingB","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET) // SPIN695.SPL (Wing Buffet)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_WingB","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
	OR(3)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),3,NUMBEROFATTACKS)
		RandomNum(5,1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_WingB","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET) // SPIN695.SPL (Wing Buffet)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_WingB","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
	OR(3)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),3,NUMBEROFATTACKS)
		RandomNum(5,1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_WingB","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET) // SPIN695.SPL (Wing Buffet)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_WingB","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),11)
	OR(3)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		CheckStatGT(LastSeenBy(Myself),3,NUMBEROFATTACKS)
		RandomNum(5,1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_WingB","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET) // SPIN695.SPL (Wing Buffet)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Dbreath","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Dbreath","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBDRAG1",LastSeenBy(Myself)) // Topaz Dragon Breath
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Dbreath","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Dbreath","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBDRAG1",LastSeenBy(Myself)) // Topaz Dragon Breath
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Dbreath","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Dbreath","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBDRAG1",LastSeenBy(Myself)) // Topaz Dragon Breath
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Dbreath","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Dbreath","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBDRAG1",LastSeenBy(Myself)) // Topaz Dragon Breath
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Dbreath","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Dbreath","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBDRAG1",LastSeenBy(Myself)) // Topaz Dragon Breath
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Dbreath","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Dbreath","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBDRAG1",LastSeenBy(Myself)) // Topaz Dragon Breath
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	CheckStatLT(Myself,1,STONESKINS)
	HaveSpell(WIZARD_STONE_SKIN) // SPWI408.SPL (Stoneskin)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WIZARD_STONE_SKIN) // SPWI408.SPL (Stoneskin)
		RemoveSpell(WIZARD_STONE_SKIN) // SPWI408.SPL (Stoneskin)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_ARMOR_OF_FAITH) // SPPR111.SPL (Armor of Faith)
	CheckStatLT(Myself,10,RESISTACID)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_ARMOR_OF_FAITH) // SPPR111.SPL (Armor of Faith)
		RemoveSpell(CLERIC_ARMOR_OF_FAITH) // SPPR111.SPL (Armor of Faith)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Conte","LOCALS")
	CheckStatLT(Myself,100,RESISTFIRE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Conte","LOCALS",FIVE_ROUNDS)
		ForceSpellRES("OHBCONTE",Myself) // Energy Containment
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(Myself,STATE_BLIND)
	HaveSpell(CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(PALADIN_PROTECTION_FROM_EVIL) // SPCL213.SPL (Protection From Evil)
	See([0.0.DEMONIC.0.0.SUMMONED_DEMON])
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,PALADIN_PROTECTION_FROM_EVIL) // SPCL213.SPL (Protection From Evil)
		RemoveSpell(PALADIN_PROTECTION_FROM_EVIL) // SPCL213.SPL (Protection From Evil)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_DEATH_WARD) // SPPR409.SPL (Death Ward)
	!CheckStatGT(Myself,0,SCRIPTINGSTATE2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_DEATH_WARD) // SPPR409.SPL (Death Ward)
		RemoveSpell(CLERIC_DEATH_WARD) // SPPR409.SPL (Death Ward)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION) // SPPR403.SPL (Free Action)
	!CheckStatGT(Myself,0,CLERIC_FREE_ACTION)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_FREE_ACTION) // SPPR403.SPL (Free Action)
		RemoveSpell(CLERIC_FREE_ACTION) // SPPR403.SPL (Free Action)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	Allegiance(Myself,EVILCUTOFF)
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	OR(4)
		See([GOODCUTOFF.0.0.CLERIC_ALL])
		See([GOODCUTOFF.0.0.DRUID_ALL])
		See([GOODCUTOFF.0.0.BARD_ALL])
		See([GOODCUTOFF.0.0.LONG_BOW])
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	Allegiance(Myself,EVILCUTOFF)
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	OR(4)
		See(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
		See(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]))
		See(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]))
		See(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	Allegiance(Myself,EVILCUTOFF)
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	OR(4)
		See(ThirdNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
		See(ThirdNearest([GOODCUTOFF.0.0.DRUID_ALL]))
		See(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]))
		See(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(SeventhNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(EighthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(NinthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	HaveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
	See(TenthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),30,LEVEL)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),30,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself)) // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself)) // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself)) // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself)) // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		RemoveSpell(WIZARD_DISPEL_MAGIC) // SPWI302.SPL (Remove Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpellRES("OHBPROG") // Protection from Good
	OR(3)
		See([GOODCUTOFF.0.0.0.0.0.MASK_GOOD])
		See(SecondNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
		See(ThirdNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBPROG",Myself) // Protection from Good
		RemoveSpellRES("OHBPROG") // Protection from Good
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(PALADIN_PROTECTION_FROM_EVIL) // SPCL213.SPL (Protection From Evil)
	OR(3)
		See([GOODCUTOFF.0.0.0.0.0.MASK_EVIL])
		See(SecondNearest([GOODCUTOFF.0.0.0.0.0.MASK_EVIL]))
		See(ThirdNearest([GOODCUTOFF.0.0.0.0.0.MASK_EVIL]))
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,PALADIN_PROTECTION_FROM_EVIL) // SPCL213.SPL (Protection From Evil)
		RemoveSpell(PALADIN_PROTECTION_FROM_EVIL) // SPCL213.SPL (Protection From Evil)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_BLUR) // SPWI201.SPL (Blur)
	!StateCheck(Myself,STATE_BLUR)
	!CheckStatGT(Player1,0,TRUE_SIGHT)
	!CheckStatGT(Player2,0,TRUE_SIGHT)
	!CheckStatGT(Player3,0,TRUE_SIGHT)
	!CheckStatGT(Player4,0,TRUE_SIGHT)
	!CheckStatGT(Player5,0,TRUE_SIGHT)
	!CheckStatGT(Player6,0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WIZARD_BLUR) // SPWI201.SPL (Blur)
		RemoveSpell(WIZARD_BLUR) // SPWI201.SPL (Blur)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See([GOODCUTOFF.0.0.LONG_BOW])
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See([GOODCUTOFF.0.0.CLERIC_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	!SpellCast(LastSeenBy(Myself),WIZARD_VOCALIZE) // SPWI219.SPL (Vocalize)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See(ThirdNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See([GOODCUTOFF.0.0.DRUID_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See(ThirdNearest([GOODCUTOFF.0.0.DRUID_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See([GOODCUTOFF.0.0.BARD_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Silence","LOCALS")
	See(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself)) // Amulet of Power
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Silence","LOCALS",THREE_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		RemoveSpell(CLERIC_SILENCE_15_FOOT) // SPPR211.SPL (Silence, 15' Radius)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See([PC.0.0.RANGER])
	Kit(LastSeenBy(Myself),FERALAN)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(SecondNearest([PC.0.0.RANGER]))
	Kit(LastSeenBy(Myself),FERALAN)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(ThirdNearest([PC.0.0.RANGER]))
	Kit(LastSeenBy(Myself),FERALAN)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(StrongestOf([PC]))
	OR(3)
		Class(LastSeenBy(Myself),FIGHTER_ALL)
		Class(LastSeenBy(Myself),RANGER_ALL)
		Class(LastSeenBy(Myself),PALADIN_ALL)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See([PC.0.0.FIGHTER_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See([PC.0.0.RANGER_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(SecondNearest([PC.0.0.RANGER_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See([PC.0.0.PALADIN_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(StrongestOf([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	Range(SecondNearest([GOODCUTOFF]),10)
	Range([GOODCUTOFF],10)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	Range(SecondNearest([GOODCUTOFF]),10)
	Range([GOODCUTOFF],10)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(FourthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_cloud","LOCALS")
	HaveSpellRES("OHBWFOG") // Wall of Fog
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!HasItemEquiped("NPMISC1",LastSeenBy(Myself)) // Jansen Spectroscopes
	!HasItemEquiped("RR#HEL02",LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_cloud","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWFOG",LastSeenBy(Myself)) // Wall of Fog
		RemoveSpellRES("OHBWFOG") // Wall of Fog
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
	AreaType(OUTDOOR)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of Reflection
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		RemoveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
	AreaType(OUTDOOR)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of Reflection
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		RemoveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
	AreaType(OUTDOOR)
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of Reflection
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		RemoveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
	AreaType(OUTDOOR)
	See(FourthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of Reflection
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		RemoveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
	AreaType(OUTDOOR)
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of Reflection
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		RemoveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
	AreaType(OUTDOOR)
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK24",LastSeenBy(Myself)) // Cloak of Reflection
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		RemoveSpell(CLERIC_CALL_LIGHTNING) // SPPR302.SPL (Call Lightning)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
	OR(4)
		See([GOODCUTOFF.0.0.BARD_ALL])
		See([GOODCUTOFF.0.0.DRUID_ALL])
		See([GOODCUTOFF.0.0.CLERIC_ALL])
		See([GOODCUTOFF.0.0.LONG_BOW])
	!HasItemEquiped("MISC5X",LastSeenBy(Myself)) // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself)) // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		RemoveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!HasItemEquiped("MISC5X",LastSeenBy(Myself)) // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself)) // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		RemoveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!HasItemEquiped("MISC5X",LastSeenBy(Myself)) // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself)) // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		RemoveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!HasItemEquiped("MISC5X",LastSeenBy(Myself)) // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself)) // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		RemoveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
	See(FourthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!HasItemEquiped("MISC5X",LastSeenBy(Myself)) // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself)) // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		RemoveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!HasItemEquiped("MISC5X",LastSeenBy(Myself)) // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself)) // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		RemoveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!HasItemEquiped("MISC5X",LastSeenBy(Myself)) // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself)) // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		RemoveSpell(WIZARD_MAGIC_MISSILE) // SPWI112.SPL (Magic Missile)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(NearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBLDRAI",LastSeenBy(Myself)) // Life Drain
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBLDRAI",LastSeenBy(Myself)) // Life Drain
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBLDRAI",LastSeenBy(Myself)) // Life Drain
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBLDRAI",LastSeenBy(Myself)) // Life Drain
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBLDRAI",LastSeenBy(Myself)) // Life Drain
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBLDRAI",LastSeenBy(Myself)) // Life Drain
END

IF
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	OR(6)
		See(Player1)
		See(Player2)
		See(Player3)
		See(Player4)
		See(Player5)
		See(Player6)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!StateCheck(WorstAC([PC]),STATE_PANIC)
	!StateCheck(WorstAC([PC]),STATE_MIRRORIMAGE)
	!CheckStatGT(WorstAC([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	CheckStatLT(WorstAC([PC]),100,RESISTSLASHING)
	CheckStatLT(WorstAC([PC]),1,STONESKINS)
	See(WorstAC([PC]))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	AttackedBy(NearestEnemyOf(Myself),DEFAULT)
	!CheckStatGT(LastAttackerOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(LastAttackerOf(Myself),STATE_PANIC)
	CheckStatLT(LastAttackerOf(Myself),100,RESISTSLASHING)
	!StateCheck(LastAttackerOf(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastAttackerOf(Myself),1,STONESKINS)
	Range(LastAttackerOf(Myself),8)
	RandomNum(3,1)
	See(LastAttackerOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	AttackedBy(NearestEnemyOf(Myself),DEFAULT)
	!CheckStatGT(LastAttackerOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(LastAttackerOf(Myself),STATE_PANIC)
	CheckStatLT(LastAttackerOf(Myself),100,RESISTSLASHING)
	!StateCheck(LastAttackerOf(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastAttackerOf(Myself),1,STONESKINS)
	Range(LastAttackerOf(Myself),4)
	See(LastAttackerOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player6,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player6,STATE_IMMOBILE)
	CheckStatLT(Player6,100,RESISTSLASHING)
	See(Player6)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player5,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player5,STATE_IMMOBILE)
	CheckStatLT(Player5,100,RESISTSLASHING)
	See(Player5)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player4,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player4,STATE_IMMOBILE)
	CheckStatLT(Player4,100,RESISTSLASHING)
	See(Player4)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player3,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player3,STATE_IMMOBILE)
	CheckStatLT(Player3,100,RESISTSLASHING)
	See(Player3)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player2,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player2,STATE_IMMOBILE)
	CheckStatLT(Player2,100,RESISTSLASHING)
	See(Player2)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player1,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player1,STATE_IMMOBILE)
	CheckStatLT(Player1,100,RESISTSLASHING)
	See(Player1)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

IF
	Global("OH_Heal","LOCALS",0)
	Global("OH_Active","LOCALS",1)
	!Range([GOODCUTOFF],30)
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	!StateCheck(Myself,STATE_BLIND)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("OH_Heal","LOCALS",0)
	Global("OH_Active","LOCALS",1)
	!Range([GOODCUTOFF],30)
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	!StateCheck(Myself,STATE_BLIND)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	OR(2)
		RandomNum(5,1)
		CombatCounter(0)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Global("OH_Heal","LOCALS",1)
	Global("OH_Active","LOCALS",1)
	!Range([GOODCUTOFF],30)
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!Allegiance(LastSeenBy(Myself),EVILCUTOFF)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),15)
END


