IF
	Global("OH_Active","LOCALS",0)
	OR(3)
		See(NearestEnemyOf(Myself))
		AttackedBy([ANYONE],DEFAULT)
		TookDamage()
THEN
	RESPONSE #100
		SetGlobal("OH_Active","LOCALS",1)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		Enemy()
		Shout(ASSIST)
		Continue()
END

IF
	Global("OH_Active","LOCALS",0)
	Heard([EVILCUTOFF],ASSIST)
	Range(LastHeardBy(Myself),25)
THEN
	RESPONSE #100
		SetGlobal("OH_Active","LOCALS",1)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		Enemy()
		Shout(ASSIST)
		MoveToObject(LastHeardBy(Myself))
END

IF
	OR(5)
		Global("OH_Active","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_PANIC)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!GlobalTimerNotExpired("OH_Rest","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		SetGlobal("OH_Cntg","LOCALS",0)
		SetGlobal("OH_Seq","LOCALS",0)
		SetGlobal("OH_MSeq","LOCALS",0)
		ApplySpell(Myself,RESTORE_FULL_HEALTH) // SPIN746.SPL (No such index)
		Rest()
END

IF
	Global("OH_Heal","LOCALS",1)
	OR(2)
		HPPercentGT(Myself,84)
		!HasItem("POTN52",Myself) // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobal("OH_Heal","LOCALS",0)
END

IF
	HPPercentLT(Myself,85)
	Global("OH_Heal","LOCALS",0)
	HasItem("POTN52",Myself) // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobal("OH_Heal","LOCALS",1)
END

IF
	Global("OH_Heal","LOCALS",1)
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("dvgldust","LOCALS",1)
	HasItem("POTN10",Myself) // Potion of Invisibility
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!CheckStatGT(Player1,0,TRUE_SIGHT)
	!CheckStatGT(Player2,0,TRUE_SIGHT)
	!CheckStatGT(Player3,0,TRUE_SIGHT)
	!CheckStatGT(Player4,0,TRUE_SIGHT)
	!CheckStatGT(Player5,0,TRUE_SIGHT)
	!CheckStatGT(Player6,0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		UseItem("POTN10",Myself) // Potion of Invisibility
		DisplayStringHead(Myself,46150) // *quaffs a potion*
END

IF
	Global("OH_Heal","LOCALS",1)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HasItem("POTN52",Myself) // Potion of Extra Healing
	HPPercentLT(Myself,85)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		UseItem("POTN52",Myself) // Potion of Extra Healing
		DisplayStringHead(Myself,46150) // *quaffs a potion*
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(Myself,STATE_BLIND)
	HaveSpell(CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
END

IF
	HasItem("HARM",Myself) // Harm
	HPGT(Player1,29)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SANCTUARY)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player1) // Cloak of Mirroring
	!CheckStat(Player1,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player1,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player1,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player1,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player1,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player1,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Attack(Player1)
END

IF
	HasItem("HARM",Myself) // Harm
	HPGT(Player2,29)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SANCTUARY)
	!StateCheck(Player2,STATE_REALLY_DEAD)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player2) // Cloak of Mirroring
	!CheckStat(Player2,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player2,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player2,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player2,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player2,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player2,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player2)
THEN
	RESPONSE #100
		Attack(Player2)
END

IF
	HasItem("HARM",Myself) // Harm
	HPGT(Player3,29)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SANCTUARY)
	!StateCheck(Player3,STATE_REALLY_DEAD)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player3) // Cloak of Mirroring
	!CheckStat(Player3,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player3,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player3,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player3,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player3,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player3,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player3)
THEN
	RESPONSE #100
		Attack(Player3)
END

IF
	HasItem("HARM",Myself) // Harm
	HPGT(Player4,29)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SANCTUARY)
	!StateCheck(Player4,STATE_REALLY_DEAD)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player4) // Cloak of Mirroring
	!CheckStat(Player4,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player4,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player4,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player4,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player4,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player4,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player4)
THEN
	RESPONSE #100
		Attack(Player4)
END

IF
	HasItem("HARM",Myself) // Harm
	HPGT(Player5,29)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SANCTUARY)
	!StateCheck(Player5,STATE_REALLY_DEAD)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player5) // Cloak of Mirroring
	!CheckStat(Player5,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player5,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player5,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player5,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player5,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player5,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player5)
THEN
	RESPONSE #100
		Attack(Player5)
END

IF
	HasItem("HARM",Myself) // Harm
	HPGT(Player6,29)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SANCTUARY)
	!StateCheck(Player6,STATE_REALLY_DEAD)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player6) // Cloak of Mirroring
	!CheckStat(Player6,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player6,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player6,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player6,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player6,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player6,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player6)
THEN
	RESPONSE #100
		Attack(Player6)
END

IF
	HasItem("SLAYLIVE",Myself) // Slay Living
	HPGT(Player1,29)
	CheckStatGT(Player1,0,SAVEVSSPELL)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SANCTUARY)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	!StateCheck(Player1,STATE_MIRRORIMAGE)
	CheckStatLT(Player1,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player1) // Cloak of Mirroring
	!CheckStat(Player1,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player1,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player1,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player1,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player1,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player1,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player1)
THEN
	RESPONSE #100
		Attack(Player1)
END

IF
	HasItem("SLAYLIVE",Myself) // Slay Living
	HPGT(Player2,29)
	CheckStatGT(Player2,0,SAVEVSSPELL)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SANCTUARY)
	!StateCheck(Player2,STATE_REALLY_DEAD)
	!StateCheck(Player2,STATE_MIRRORIMAGE)
	CheckStatLT(Player2,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player2) // Cloak of Mirroring
	!CheckStat(Player2,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player2,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player2,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player2,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player2,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player2,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player2)
THEN
	RESPONSE #100
		Attack(Player2)
END

IF
	HasItem("SLAYLIVE",Myself) // Slay Living
	HPGT(Player3,29)
	CheckStatGT(Player3,0,SAVEVSSPELL)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SANCTUARY)
	!StateCheck(Player3,STATE_REALLY_DEAD)
	!StateCheck(Player3,STATE_MIRRORIMAGE)
	CheckStatLT(Player3,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player3) // Cloak of Mirroring
	!CheckStat(Player3,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player3,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player3,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player3,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player3,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player3,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player3)
THEN
	RESPONSE #100
		Attack(Player3)
END

IF
	HasItem("SLAYLIVE",Myself) // Slay Living
	HPGT(Player4,29)
	CheckStatGT(Player4,0,SAVEVSSPELL)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SANCTUARY)
	!StateCheck(Player4,STATE_REALLY_DEAD)
	!StateCheck(Player4,STATE_MIRRORIMAGE)
	CheckStatLT(Player4,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player4) // Cloak of Mirroring
	!CheckStat(Player4,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player4,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player4,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player4,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player4,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player4,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player4)
THEN
	RESPONSE #100
		Attack(Player4)
END

IF
	HasItem("SLAYLIVE",Myself) // Slay Living
	HPGT(Player5,29)
	CheckStatGT(Player5,0,SAVEVSSPELL)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SANCTUARY)
	!StateCheck(Player5,STATE_REALLY_DEAD)
	!StateCheck(Player5,STATE_MIRRORIMAGE)
	CheckStatLT(Player5,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player5) // Cloak of Mirroring
	!CheckStat(Player5,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player5,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player5,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player5,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player5,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player5,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player5)
THEN
	RESPONSE #100
		Attack(Player5)
END

IF
	HasItem("SLAYLIVE",Myself) // Slay Living
	HPGT(Player6,29)
	CheckStatGT(Player6,0,SAVEVSSPELL)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SANCTUARY)
	!StateCheck(Player6,STATE_REALLY_DEAD)
	!StateCheck(Player6,STATE_MIRRORIMAGE)
	CheckStatLT(Player6,50,RESISTMAGIC)
	!HasItemEquiped("CLCK26",Player6) // Cloak of Mirroring
	!CheckStat(Player6,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Player6,0,WIZARD_SPELL_TRAP)
	!CheckStatGT(Player6,0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player6,0,WIZARD_SPELL_TURNING)
	!CheckStat(Player6,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player6,7,WIZARD_SPELL_IMMUNITY)
	InMyArea(Player6)
THEN
	RESPONSE #100
		Attack(Player6)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast([GOODCUTOFF.0.0.LONG_BOW],WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast([GOODCUTOFF.0.0.LONG_BOW],WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast([GOODCUTOFF.0.0.LONG_BOW],WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast([GOODCUTOFF.0.0.LONG_BOW],WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.LONG_BOW]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD) // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD) // SPWI213.SPL (Stinking Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL) // SPWI502.SPL (Cloudkill)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG) // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	Global("OH_Cloud","LOCALS",1)
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR) // SPPR318.SPL (Zone of Sweet Air)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobal("OH_Cloud","LOCALS",0)
		Spell(Myself,CLERIC_ZONE_OF_SWEET_AIR) // SPPR318.SPL (Zone of Sweet Air)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!See([GOODCUTOFF])
	Detect([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),80,STEALTH)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	HaveSpell(CLERIC_TRUE_SIGHT) // SPPR505.SPL (True Seeing)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_TRUE_SIGHT) // SPPR505.SPL (True Seeing)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck([EVILCUTOFF],STATE_PANIC)
	See([EVILCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(SecondNearest([EVILCUTOFF]),STATE_PANIC)
	See(SecondNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(ThirdNearest([EVILCUTOFF]),STATE_PANIC)
	See(ThirdNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(FourthNearest([EVILCUTOFF]),STATE_PANIC)
	See(FourthNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(FifthNearest([EVILCUTOFF]),STATE_PANIC)
	See(FifthNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(SixthNearest([EVILCUTOFF]),STATE_PANIC)
	See(SixthNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR) // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck([EVILCUTOFF],STATE_STUNNED)
		CheckStatGT([EVILCUTOFF],0,HELD)
	See([EVILCUTOFF])
	HaveSpell(CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(SecondNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(SecondNearest([EVILCUTOFF]),0,HELD)
	See(SecondNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(ThirdNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(ThirdNearest([EVILCUTOFF]),0,HELD)
	See(ThirdNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(FourthNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(FourthNearest([EVILCUTOFF]),0,HELD)
	See(FourthNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(FifthNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(FifthNearest([EVILCUTOFF]),0,HELD)
	HaveSpell(CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	See(FifthNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(SixthNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(SixthNearest([EVILCUTOFF]),0,HELD)
	HaveSpell(CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	See(SixthNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS) // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck([EVILCUTOFF],STATE_FEEBLEMINDED)
		StateCheck([EVILCUTOFF],STATE_BLIND)
	See([EVILCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(SecondNearest([EVILCUTOFF]),STATE_FEEBLEMINDED)
		StateCheck(SecondNearest([EVILCUTOFF]),STATE_BLIND)
	See(SecondNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(ThirdNearest([EVILCUTOFF]),STATE_FEEBLEMINDED)
		StateCheck(ThirdNearest([EVILCUTOFF]),STATE_BLIND)
	See(ThirdNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(FourthNearest([EVILCUTOFF]),STATE_FEEBLEMINDED)
		StateCheck(FourthNearest([EVILCUTOFF]),STATE_BLIND)
	See(FourthNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(FifthNearest([EVILCUTOFF]),STATE_FEEBLEMINDED)
		StateCheck(FifthNearest([EVILCUTOFF]),STATE_BLIND)
	See(FifthNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(SixthNearest([EVILCUTOFF]),STATE_FEEBLEMINDED)
		StateCheck(SixthNearest([EVILCUTOFF]),STATE_BLIND)
	See(SixthNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_CURE_DISEASE) // SPPR317.SPL (Cure Disease)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(Myself,STATE_POISONED)
	HaveSpell(CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See([EVILCUTOFF])
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(SecondNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(ThirdNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(FourthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(FifthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(SixthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON) // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(Myself,STATE_BLIND)
		StateCheck(Myself,STATE_POISONED)
	HaveSpell(CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck([EVILCUTOFF],STATE_POISONED)
		StateCheck([EVILCUTOFF],STATE_BLIND)
	See([EVILCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(SecondNearest([EVILCUTOFF]),STATE_POISONED)
		StateCheck(SecondNearest([EVILCUTOFF]),STATE_BLIND)
	See(SecondNearest([EVILCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(ThirdNearest([EVILCUTOFF]),STATE_POISONED)
		StateCheck(ThirdNearest([EVILCUTOFF]),STATE_BLIND)
	See(ThirdNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(FourthNearest([EVILCUTOFF]),STATE_POISONED)
		StateCheck(FourthNearest([EVILCUTOFF]),STATE_BLIND)
	See(FourthNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(FifthNearest([EVILCUTOFF]),STATE_POISONED)
		StateCheck(FifthNearest([EVILCUTOFF]),STATE_BLIND)
	See(FifthNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(SixthNearest([EVILCUTOFF]),STATE_POISONED)
		StateCheck(SixthNearest([EVILCUTOFF]),STATE_BLIND)
	See(SixthNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_NEUTRALIZE_POISON) // SPPR404.SPL (Neutralize Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!See([GOODCUTOFF])
	Detect([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),80,STEALTH)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	HaveSpell(CLERIC_TRUE_SIGHT) // SPPR505.SPL (True Seeing)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_TRUE_SIGHT) // SPPR505.SPL (True Seeing)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_TRUE_SIGHT) // SPPR505.SPL (True Seeing)
	CheckStat(Myself,0,TRUE_SIGHT)
	OR(7)
		StateCheck(Player1,STATE_NOT_TARGETABLE)
		StateCheck(Player2,STATE_NOT_TARGETABLE)
		StateCheck(Player3,STATE_NOT_TARGETABLE)
		StateCheck(Player4,STATE_NOT_TARGETABLE)
		StateCheck(Player5,STATE_NOT_TARGETABLE)
		StateCheck(Player6,STATE_NOT_TARGETABLE)
		Detect([GOODCUTOFF.0.0.0.0.ILLUSIONARY])
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_TRUE_SIGHT) // SPPR505.SPL (True Seeing)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("dvgldust","LOCALS",1)
	HasItem("POTN10",Myself) // Potion of Invisibility
	!HasItem("HARM",Myself) // Harm
	!HasItem("SLAYLIVE",Myself) // Slay Living
	OR(2)
		HaveSpell(CLERIC_HARM) // SPPR608.SPL (Harm)
		HaveSpell(CLERIC_SLAY_LIVING) // SPPR511.SPL (Slay Living)
	DifficultyGT(EASY)
	!CheckStatGT(Player1,0,TRUE_SIGHT)
	!CheckStatGT(Player2,0,TRUE_SIGHT)
	!CheckStatGT(Player3,0,TRUE_SIGHT)
	!CheckStatGT(Player4,0,TRUE_SIGHT)
	!CheckStatGT(Player5,0,TRUE_SIGHT)
	!CheckStatGT(Player6,0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		UseItem("POTN10",Myself) // Potion of Invisibility
		DisplayStringHead(Myself,46150) // *quaffs a potion*
END

IF
	HaveSpell(CLERIC_SANCTUARY) // SPPR109.SPL (Sanctuary)
	!HasItem("POTN10",Myself) // Potion of Invisibility
	!HasItem("HARM",Myself) // Harm
	!HasItem("SLAYLIVE",Myself) // Slay Living
	OR(2)
		HaveSpell(CLERIC_HARM) // SPPR608.SPL (Harm)
		HaveSpell(CLERIC_SLAY_LIVING) // SPPR511.SPL (Slay Living)
	DifficultyGT(EASY)
	!StateCheck(Myself,STATE_INVISIBLE)
	!CheckStat(Myself,1,SANCTUARY)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HPPercentLT(Myself,50)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Player1,0,TRUE_SIGHT)
	!CheckStatGT(Player2,0,TRUE_SIGHT)
	!CheckStatGT(Player3,0,TRUE_SIGHT)
	!CheckStatGT(Player4,0,TRUE_SIGHT)
	!CheckStatGT(Player5,0,TRUE_SIGHT)
	!CheckStatGT(Player6,0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_SANCTUARY) // SPPR109.SPL (Sanctuary)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_WORD) // SPPR715.SPL (Unholy Word)
	!Difficulty(EASIEST)
	See([GOODCUTOFF.0.0.LONG_BOW.0.0.MASK_GOOD])
	!Gender(LastSeenBy(Myself),ILLUSIONARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		Spell(Myself,CLERIC_UNHOLY_WORD) // SPPR715.SPL (Unholy Word)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_WORD) // SPPR715.SPL (Unholy Word)
	!Difficulty(EASIEST)
	See([GOODCUTOFF.0.0.CLERIC_ALL.0.0.MASK_GOOD])
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		Spell(Myself,CLERIC_UNHOLY_WORD) // SPPR715.SPL (Unholy Word)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_WORD) // SPPR715.SPL (Unholy Word)
	!Difficulty(EASIEST)
	See([GOODCUTOFF.0.0.DRUID_ALL.0.0.MASK_GOOD])
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		Spell(Myself,CLERIC_UNHOLY_WORD) // SPPR715.SPL (Unholy Word)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_WORD) // SPPR715.SPL (Unholy Word)
	!Difficulty(EASIEST)
	See([GOODCUTOFF.0.0.BARD_ALL.0.0.MASK_GOOD])
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		Spell(Myself,CLERIC_UNHOLY_WORD) // SPPR715.SPL (Unholy Word)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_HOLY_POWER) // SPPR412.SPL (Holy Power)
	CheckStatLT(Myself,18,STR)
	OR(2)
		HaveSpell(CLERIC_HARM) // SPPR608.SPL (Harm)
		HaveSpell(CLERIC_SLAY_LIVING) // SPPR511.SPL (Slay Living)
	DifficultyGT(EASY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_HOLY_POWER) // SPPR412.SPL (Holy Power)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!HasItem("HARM",Myself) // Harm
	!HasItem("SLAYLIVE",Myself) // Slay Living
	HaveSpell(CLERIC_HARM) // SPPR608.SPL (Harm)
	DifficultyGT(EASY)
	OR(2)
		RandomNum(2,1)
		StateCheck(Myself,STATE_INVISIBLE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #10
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_HARM) // SPPR608.SPL (Harm)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_REGENERATE) // SPPR711.SPL (Regeneration)
	OR(6)
		Help(SixthNearest([ENEMY]))
		Help(FifthNearest([ENEMY]))
		Help(FourthNearest([ENEMY]))
		Help(ThirdNearest([ENEMY]))
		Help(SecondNearest([ENEMY]))
		Help([ENEMY])
	!StateCheck(LastHelp(Myself),STATE_BERSERK | STATE_PANIC | STATE_CHARMED | STATE_CONFUSED)
	HPPercentLT(LastHelp(Myself),100)
	!StateCheck(LastHelp(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastHelp(Myself),STATE_REALLY_DEAD)
	CheckStat(LastHelp(Myself),0,MINORGLOBE)
	!CheckStatGT(LastHelp(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastHelp(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastHelp(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastHelp(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastHelp(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	Allegiance(LastHelp(Myself),ENEMY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastHelp(Myself),CLERIC_REGENERATE) // SPPR711.SPL (Regeneration)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_HEAL) // SPPR607.SPL (Heal)
	OR(6)
		Help(SixthNearest([ENEMY]))
		Help(FifthNearest([ENEMY]))
		Help(FourthNearest([ENEMY]))
		Help(ThirdNearest([ENEMY]))
		Help(SecondNearest([ENEMY]))
		Help([ENEMY])
	!StateCheck(LastHelp(Myself),STATE_BERSERK | STATE_PANIC | STATE_CHARMED | STATE_CONFUSED)
	HPPercentLT(LastHelp(Myself),100)
	!StateCheck(LastHelp(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastHelp(Myself),STATE_REALLY_DEAD)
	CheckStat(LastHelp(Myself),0,MINORGLOBE)
	!CheckStatGT(LastHelp(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastHelp(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastHelp(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastHelp(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastHelp(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	Allegiance(LastHelp(Myself),ENEMY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastHelp(Myself),CLERIC_HEAL) // SPPR607.SPL (Heal)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Dhar","LOCALS")
	HaveSpell(CLERIC_DEFENSIVE_HARMONY) // SPPR406.SPL (Defensive Harmony)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStat(Myself,0,CLERIC_DEFENSIVE_HARMONY)
	Range([EVILCUTOFF],12)
	Range(SecondNearest([EVILCUTOFF]),12)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Dhar","LOCALS",FOUR_ROUNDS)
		Spell(Myself,CLERIC_DEFENSIVE_HARMONY) // SPPR406.SPL (Defensive Harmony)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_CHANT) // SPPR203.SPL (Chant)
	!StateCheck(Myself,STATE_CHANT)
	Range([EVILCUTOFF],12)
	Range(SecondNearest([EVILCUTOFF]),12)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_CHANT) // SPPR203.SPL (Chant)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_BLESS) // SPPR101.SPL (Bless)
	!StateCheck(Myself,STATE_BLESS)
	Range([EVILCUTOFF],12)
	Range(SecondNearest([EVILCUTOFF]),12)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_BLESS) // SPPR101.SPL (Bless)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_ARMOR_OF_FAITH) // SPPR111.SPL (Armor of Faith)
	OR(2)
		!HaveSpell(CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
		RandomNum(6,1)
	CheckStatLT(Myself,10,MAGICDAMAGERESISTANCE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_ARMOR_OF_FAITH) // SPPR111.SPL (Armor of Faith)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	OR(3)
		CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
		CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	OR(3)
		CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
		CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	OR(3)
		CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
		CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(FourthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	OR(3)
		CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
		CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(FifthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	OR(3)
		CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
		CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(SixthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	OR(3)
		CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
		CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
		CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_STORM_OF_VENGEANCE) // SPPR722.SPL (Storm of Vengeance)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
	!Difficulty(EASIEST)
	See([PC.0.0.MAGE])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself)) // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.MAGE]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself)) // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
	!Difficulty(EASIEST)
	See([PC.0.0.BARD])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself)) // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.BARD]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself)) // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
	!Difficulty(EASIEST)
	See([PC.0.0.THIEF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself)) // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.THIEF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself)) // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
	!Difficulty(EASIEST)
	See([PC.0.0.MAGE_THIEF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself)) // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.MAGE_THIEF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself)) // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FINGER_OF_DEATH) // SPPR708.SPL (Finger of Death)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See([GOODCUTOFF.0.0.0.0.0.MASK_GOOD])
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(SecondNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(ThirdNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(FourthNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(FifthNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!Difficulty(EASIEST)
	See(SixthNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself)) // Cloak of Mirroring
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT) // SPPR314.SPL (Unholy Blight)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!HasItem("HARM",Myself) // Harm
	!HasItem("SLAYLIVE",Myself) // Slay Living
	HaveSpell(CLERIC_SLAY_LIVING) // SPPR511.SPL (Slay Living)
	DifficultyGT(EASY)
	OR(2)
		RandomNum(2,1)
		StateCheck(Myself,STATE_INVISIBLE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #10
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,CLERIC_SLAY_LIVING) // SPPR511.SPL (Slay Living)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
	See(FourthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself)) // Cloak of Mirroring
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE) // SPPR503.SPL (Flame Strike)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See([PC.0.0.MAGE])
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(SecondNearest([PC.0.0.MAGE]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(ThirdNearest([PC.0.0.MAGE]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See([PC.0.0.MAGE_THIEF])
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(SecondNearest([PC.0.0.MAGE_THIEF]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(ThirdNearest([PC.0.0.MAGE_THIEF]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See([PC.0.0.BARD_ALL])
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(SecondNearest([PC.0.0.BARD_ALL]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See([PC.0.0.THIEF])
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(SecondNearest([PC.0.0.THIEF]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See([PC.0.0.FIGHTER_ALL])
	!Race(LastSeenBy(Myself),ELF)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("NPCHAN",LastSeenBy(Myself)) // Corthala Family Armor
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
	!HasItemEquipedReal("STAF11",LastSeenBy(Myself)) // Staff of the Magi
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See(SecondNearest([PC.0.0.FIGHTER_ALL]))
	!Race(LastSeenBy(Myself),ELF)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("NPCHAN",LastSeenBy(Myself)) // Corthala Family Armor
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
	!HasItemEquipedReal("STAF11",LastSeenBy(Myself)) // Staff of the Magi
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See(ThirdNearest([PC.0.0.FIGHTER_ALL]))
	!Race(LastSeenBy(Myself),ELF)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("NPCHAN",LastSeenBy(Myself)) // Corthala Family Armor
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
	!HasItemEquipedReal("STAF11",LastSeenBy(Myself)) // Staff of the Magi
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See([PC.0.0.RANGER_ALL])
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("NPCHAN",LastSeenBy(Myself)) // Corthala Family Armor
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See(SecondNearest([PC.0.0.RANGER_ALL]))
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("NPCHAN",LastSeenBy(Myself)) // Corthala Family Armor
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See(ThirdNearest([PC.0.0.RANGER_ALL]))
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("NPCHAN",LastSeenBy(Myself)) // Corthala Family Armor
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See([PC.0.0.PALADIN_ALL])
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See(SecondNearest([PC.0.0.PALADIN_ALL]))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	DifficultyGT(EASY)
	See(ThirdNearest([PC.0.0.PALADIN_ALL]))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("HELM06",LastSeenBy(Myself)) // Helm of Charm Protection
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	!HasItemEquipedReal("SW1H35",LastSeenBy(Myself)) // Adjatha the Drinker +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION) // SPPR405.SPL (Mental Domination)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
	!Difficulty(EASIEST)
	See([GOODCUTOFF.HUMANOID])
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself)) // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself)) // Edventar's Gift
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen +2
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself)) // Arbane's Sword +2
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself)) // Spider's Bane +2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
	!Difficulty(EASIEST)
	See(SecondNearest([GOODCUTOFF.HUMANOID]))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself)) // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself)) // Edventar's Gift
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen +2
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself)) // Arbane's Sword +2
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself)) // Spider's Bane +2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
	!Difficulty(EASIEST)
	See(ThirdNearest([GOODCUTOFF.HUMANOID]))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself)) // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself)) // Edventar's Gift
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen +2
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself)) // Arbane's Sword +2
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself)) // Spider's Bane +2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
	!Difficulty(EASIEST)
	See(FourthNearest([GOODCUTOFF.HUMANOID]))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself)) // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself)) // Edventar's Gift
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen +2
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself)) // Arbane's Sword +2
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself)) // Spider's Bane +2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
	!Difficulty(EASIEST)
	See(FifthNearest([GOODCUTOFF.HUMANOID]))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself)) // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself)) // Edventar's Gift
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen +2
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself)) // Arbane's Sword +2
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself)) // Spider's Bane +2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
	!Difficulty(EASIEST)
	See(SixthNearest([GOODCUTOFF.HUMANOID]))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself)) // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself)) // Edventar's Gift
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself)) // Sword of Arvoreen +2
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself)) // Arbane's Sword +2
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself)) // Spider's Bane +2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself)) // Spear of the Unicorn +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See([GOODCUTOFF])
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(FourthNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(FifthNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_POISON) // SPPR411.SPL (Poison)
	See(SixthNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSDEATH)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("AMUL22",LastSeenBy(Myself)) // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself)) // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself)) // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself)) // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself)) // Albruin +1
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),CLERIC_POISON) // SPPR411.SPL (Poison)
END

IF
	!Global("OH_Heal","LOCALS",1)
	!GlobalTimerExpired("OH_Cast","LOCALS")
	CheckStatLT(Myself,1,SANCTUARY)
	!HaveAnySpells()
	!StateCheck(Myself,STATE_INVISIBLE)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Global("OH_Heal","LOCALS",0)
	Global("OH_Active","LOCALS",1)
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	!StateCheck(Myself,STATE_BLIND)
	OR(2)
		RandomNum(5,1)
		CombatCounter(0)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Global("OH_Heal","LOCALS",1)
	Global("OH_Active","LOCALS",1)
	!See([GOODCUTOFF])
	RandomNum(2,1)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	!HaveSpell(CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	HaveSpell(CLERIC_HOLD_PERSON) // SPPR208.SPL (Hold Person)
	!StateCheck(Myself,STATE_INVISIBLE)
	!CheckStat(Myself,1,SANCTUARY)
	OR(4)
		HitBy([GOODCUTOFF],CRUSHING)
		HitBy([GOODCUTOFF],PIERCING)
		HitBy([GOODCUTOFF],SLASHING)
		Range([GOODCUTOFF],6)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	Global("OH_Heal","LOCALS",1)
	GlobalTimerNotExpired("OH_Cast","LOCALS")
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalkContinuous()
END


